# NumPy Array Operations!!

In [1]:
import numpy as np

## Index Slicing

In [4]:
a = np.array([[17, 57, 18],
               [28, 25, 20],
               [18, 3, 7]])
print(a)

[[17 57 18]
 [28 25 20]
 [18  3  7]]


In [8]:
print(a[2, 0])

18


to get entire row:

In [4]:
print(a[0])

[17 57 18]


to get entire column:


In [5]:
print(a[:, 1])

[57 25  3]


## Sorting

In [6]:
b = np.array([[4, 7, 1],
             [8, 2, 5],
             [9, 6, 3]])
print(b)

[[4 7 1]
 [8 2 5]
 [9 6 3]]


np.sort arranges the values by row, in ascending order

In [7]:
b_s = np.sort(b)
print(b_s)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


sorting an array by columns, we simply pass axis=0

In [8]:
b_s_c = np.sort(b, axis=0)
print(b_s_c)

[[4 2 1]
 [8 6 3]
 [9 7 5]]


## Filtering

In [9]:
numbers = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10]])
odd_numbers = numbers[numbers % 2 != 0]
print(f"{odd_numbers} are odd")

[1 3 5 7 9] are odd


## Masking

In [10]:
mask = numbers < 6
print(numbers[mask])

[1 2 3 4 5]


## Adding and removing data


In [37]:
yo = np.array([[1, 2], [3, 4]])
gurt = np.array([[5, 6]])

print(yo)
print()
print(gurt)

[[1 2]
 [3 4]]

[[5 6]]


### vstack is used to add/stack two arrays by rows

In [39]:
yogurt = np.vstack((yo, gurt))
print(yogurt)

[[1 2]
 [3 4]
 [5 6]]


### hstack is used to add/stack two arrays by columns

In [43]:
column = np.array([[7], [8]])
gurtyo = np.hstack((yo, column))
print(gurtyo)

[[1 2 7]
 [3 4 8]]


### Concatenation can be done, if the shape of arrays are same

In [21]:
mostu = np.concatenate((yo, gurt))
print(mostu)

[11 27 72 43]


concatenate() is better than hstack, vstack, it works on 3D arrays too, its more flexible and versatile.

### Array Compatibility

Arrays must have same shape to be compatible for various purposes and operations. compatibility can be checked through:

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print(f"Compatibility is {a.shape == b.shape} for a & b")
print(f"Compatibility is {a.shape == c.shape} for a & c")
print(f"Compatibility is {b.shape == c.shape} for b & c")
print(f"Compatibility is {a.shape == b.shape == c.shape} for a, b & c")

Compatibility is False for a & b
Compatibility is True for a & c
Compatibility is False for b & c
Compatibility is False for a, b & c
