In [1]:
import numpy as np

In [2]:
a = np.arange(-12, 120, 12)
print(a)

[-12   0  12  24  36  48  60  72  84  96 108]


In [3]:
b = []
for i in range(-12, 120, 12):
    b.append(i)
print(b)

[-12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108]


In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
np.array([[19, 28, 37], [46, 55, 64]])

array([[19, 28, 37],
       [46, 55, 64]])

In [6]:
o = np.array([[[14, 23], [42, 51],
          [69, 78], [87, 96]]])
print(o)
o.ndim

[[[14 23]
  [42 51]
  [69 78]
  [87 96]]]


3

In [7]:
sevens = np.full((4, 5), 7)
print(sevens)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


### Taking transpose of sevens, with .T

In [8]:
sneves = sevens.T
print(sneves)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
